{{with merge (dict "component" "alerter" "command" "assemblyline_core.alerter.run_alerter") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "workflow" "command" "assemblyline_core.workflow.run_workflow") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "expiry" "command" "assemblyline_core.expiry.run_expiry") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "ingester-ingest" "command" "assemblyline_core.ingester.run_ingest") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "ingester-internal" "command" "assemblyline_core.ingester.run_internal") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "ingester-submit" "command" "assemblyline_core.ingester.run_submit") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "metrics" "command" "assemblyline_core.metrics.run_metrics_aggregator") . }}
  {{template "assemblyline.coreServiceNoCheck" .}}
{{end}}
---
{{with merge (dict "component" "statistics" "command" "assemblyline_core.metrics.run_statistics_aggregator") . }}
  {{template "assemblyline.coreServiceNoCheck" .}}
{{end}}
---
{{with merge (dict "component" "es-metrics" "command" "assemblyline_core.metrics.es_metrics") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "heartbeat" "command" "assemblyline_core.metrics.run_heartbeat_manager") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "plumber" "command" "assemblyline_core.plumber.run_plumber") . }}
  {{template "assemblyline.coreService" .}}
{{end}}
---
{{with merge (dict "component" "dispatcher" "command" "assemblyline_core.dispatching" "replicas" .Values.dispatcherInstances ) . }}
  {{template "assemblyline.coreService" .}}
{{end}}
