apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler
  labels:
    app: assemblyline
    section: core
    component: scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: scaler
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: scaler
    spec:
      serviceAccountName: {{ .Release.Name }}-scaling-manager
      priorityClassName: al-core-priority
      containers:
        - name: scaler
          image: {{ .Values.assemblylineCoreImage }}:{{ .Values.coreVersion }}
          imagePullPolicy: Always
          command: ['python', '-m', 'assemblyline_core.scaler.run_scaler']
          volumeMounts:
          {{ include "assemblyline.coreMounts" . | indent 12 }}
            - name: update-directory
              mountPath: /mount/update_root/
          env:
          {{ include "assemblyline.coreEnv" . | indent 12 }}
            - name: KUBERNETES_AL_CONFIG
              value: {{ .Release.Name }}-global-config
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FILE_UPDATE_VOLUME
              value: update-directory
            - name: FILE_UPDATE_DIRECTORY
              value: /mount/update_root/
#          livenessProbe:
#            exec:
#              command: [ "bash", "-c", "if [[ ! `find /tmp/heartbeat -newermt '-30 seconds'` ]]; then false; fi" ]
#            initialDelaySeconds: 30
#            periodSeconds: 30
      volumes:
      {{ include "assemblyline.coreVolumes" . | indent 8 }}
        - name: update-directory
          persistentVolumeClaim:
            claimName: update-directory